name: diab_prediction
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - seaborn
  - jupyter
  - pip
  # pytorch
  - pytorch
  - torchvision
  - cudatoolkit=10.2
  - GPutil
  - tqdm
  - wfdb
